### PR TITLE
PHPC-335: Create debug handlers for BSON type classes

### PR DESCRIPTION
**Pull request by jmikola**
https://jira.mongodb.org/browse/PHPC-335

### CODE REVIEW

**Comment by derickr** [comment]
LGTM

**Comment by bjori** [comment]
I'm allergic to skipifs.
Any reason bson-utcdatetime-002 can't do 
```
%rint(|string(13) "|%r1416445411987%r"|)%r
```
?

**Comment by jmikola** [comment]
@bjori: It's totally possible to use that for the EXPECTF, but the main difference was in constructing the UTCDateTime objects. Those are really two different tests.

**Comment by bjori** [comment]
Why ? The string format must work in both.
And this is testing a debug handler, the integer literal doesn't provide any value here

**Comment by jmikola** [comment]
Good point. Will do: https://jira.mongodb.org/browse/PHPC-414

**Pull request merged**
